apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-center
spec:
  selector:
    matchLabels:
      app: management-center
  template:
    metadata:
      labels:
        app: management-center
    spec:
      containers:
      - name: management-center
        image: hazelcast/management-center
---
kind: Service
apiVersion: v1
metadata:
  name: management-center
spec:
  type: NodePort
  selector:
    app: management-center
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: management-center
spec:
  host: management-center-dev.apps.c3smonkey.ch
  to:
    kind: Service
    name: management-center
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
      host: management-center-dev.apps.c3smonkey.ch
      routerName: router
      wildcardPolicy: None
