apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## TODO Namespace
namespace: dev

#nameSuffix: -v1

resources:
  - ../../base

# Patch Deployment
patchesStrategicMerge:
  - patch-spring-profile.yaml
  - patch-limits.yaml
  - patch-liveness-readiness.yaml
# Hazelcast not working - Member don`t see each others.
# todo k scale --replicas=2 deployment hazelcast-demoservice
#  - patch-replicas.yaml

# ConfigMap
configMapGenerator:
  - files:
      - config-files/application.yaml
    name: app-config


