apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: c3smonkey/template
          # TODO Change name
          name: hazelcast-demo
          ports:
            - containerPort: 8080
              name: 8080-tcp
              protocol: TCP
            - containerPort: 5701
              name: 5701-tcp
              protocol: TCP
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
            timeoutSeconds: 5
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            httpGet:
              path: /actuator/health
              port: 8080
      restartPolicy: Always
